[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sdl2 = "0.35"
image = "0.24"
nalgebra = "0.30"
wavefront_obj = "10.0"
rand = "0.8"
anyhow = "1.0"
thiserror = "1.0"
indicatif = "0.16"
