[Camera]
width = 400
height = 225
position = [-2.5, 0.0, 2.0]
focal_distance = 0.1
field_of_view = 120.0
rotation = [0.0, 0.5, 0.0]

[[Scene]]
type = "ModelObj"
path = "cubo.obj"

[[Scene]]
type = "Sphere"
center = [0.0, -2.0, 1.0]
radius = 1.0
[Scene.material]
type = "Lambertian"
albedo = [0.8, 0.2, 0.2]

[[Scene]]
type = "Sphere"
center = [0.0, 0.0, 1.0]
radius = 1.0
[Scene.material]
type = "Specular"
albedo = [0.8, 0.8, 0.8]

[[Scene]]
type = "Sphere"
center = [0.0, 1.5, 1.5]
scale = [1.0, 0.5, 1.5]
radius = 1.0
[Scene.material]
type = "Specular"
albedo = [0.8, 0.2, 0.2]

[[Scene]]
type = "Triangle"
vertices = [
	[-200.0, -100.0, 0.0],
	[100.0, 200.0, 0.0],
	[100.0, -100.0, 0.0]]
[Scene.material]
type = "Lambertian"
albedo = [0.6, 0.5, 0.1]

[[Scene]]
type = "Triangle"
vertices = [
	[-1.0, 1.0, 0.01],
	[-1.0, 2.0, 0.01],
	[0.0, 2.0, 0.01]]
[Scene.material]
type = "Specular"
albedo = [0.2, 0.1, 0.9]

[[Scene]]
type = "Sphere"
center = [0.0, 0.0, 3.0]
radius = 0.8
[Scene.material]
type = "Emitter"
albedo = [0.6, 0.6, 0.6]
